export default function Home() {
  return (
    <>
      <div>
        <iframe
          src="https://player.twitch.tv/?channel=gaules&parent=gta-rp-stream-front.vercel.app"
          height="550"
          width="950"
          allowFullScreen
        ></iframe>
      </div>
      <div>
        <iframe
          src="https://player.twitch.tv/?channel=luquet4&parent=gta-rp-stream-front.vercel.app"
          height="550"
          width="950"
          allowFullScreen
        ></iframe>
      </div>
      <div>
        <iframe
          src="https://player.twitch.tv/?channel=luanz7_&parent=gta-rp-stream-front.vercel.app"
          height="550"
          width="950"
          allowFullScreen
        ></iframe>
      </div>
    </>
  );
}
